import { test, expect } from "@playwright/test";
var homePage = "http://localhost:3000/";

test("should navigate to the weeds page", async ({ page }) => {
  // Start from the index page (the baseURL is set via the webServer in the playwright.config.ts)
  await page.goto(homePage);
  // Find an element with the text 'Weeds data &rarr;' and click on it
  await page.click("text=Click for weeds data!");
  // The new URL should be "/weeds" (baseURL is used there)
  await expect(page).toHaveURL("http://localhost:3000/weeds");
  // The new page should contain an h1 with "Learn About Weeds!"
  await expect(page.locator("h1")).toContainText("Learn About Weeds!");
});

test.describe("Main content tests", () => {
  test("Should contain a heading", async ({ page }) => {
    await page.goto(homePage);
    await expect(page.locator("h1")).toContainText("Weeds");
  });
  test("Should contain a description", async ({ page }) => {
    await page.goto(homePage);
    await expect(page.locator("main > p")).toContainText(
      "Learn more about Weeds!"
    );
  });
});

test.describe("Header tag area", () => {
  test("Contains the head tag and its contents", async ({ page }) => {
    await page.goto(homePage); // must have a place to go to first
    await expect(page).toHaveTitle("Learn About Weeds");
    const metaDescription = page.locator('meta[name="description"]');
    await expect(metaDescription).toHaveAttribute(
      "content",
      "Generated by create next app"
    );
  });
});
