import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Learn About Weeds</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>Weeds</h1>
        <p className={styles.description}>Learn more about Weeds!</p>
        <div className={styles.grid}>
          <a href="/weeds" className={styles.card}>
            <h3>Click for weeds data!</h3>
          </a>
        </div>
      </main>
    </>
  );
}
